version: "3.5"
services:
  db:
    container_name: rb
    ports:
      - "5432:5432"
    image: postgres:latest
    command: postgres -c max_connections=50
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.85"
          memory: "2.4GB"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    network_mode: host

  api1:
    image: elixir
    depends_on:
      - db
    environment:
      PORT: 4000
      RELEASE_COOKIE: "secret_cookie"
      PEER_NODES: "api2@"
      RELEASE_NODE: "api1"
      POOL_SIZE: 200
      DB_HOST: localhost
    healthcheck:
      test: curl -f http://localhost:4000
    deploy:
      resources:
        limits:
          cpus: "0.275"
          memory: "0.25GB"
    network_mode: host

  api2:
    image: elixir
    depends_on:
      - api1
    environment:
      PORT: 4001
      RELEASE_COOKIE: "secret_cookie"
      PEER_NODES: "api1@"
      RELEASE_NODE: "api2"
      POOL_SIZE: 200
      DB_HOST: localhost
    healthcheck:
      test: curl -f http://localhost:4001
    deploy:
      resources:
        limits:
          cpus: "0.275"
          memory: "0.25GB"
    network_mode: host

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.1GB"
    network_mode: host
